<a href="https://colab.research.google.com/github/avbalwin/S2-Codebase/blob/main/Experiment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ExperimentNo.1

**Inroducing python as a tool for computational mathematics**

## AIM


To introduce Python programming fundamentals and demonstrate its use as a computational tool for basic mathematical operations relevant to Engineering Mathematics.



### 1. Hello World
The classic first program for any language.

In [ ]:
print("Hello, World!")

Hello, World!


### 2. Basic Arithmetic Operations
Simple operations like addition, subtraction, multiplication and division.

In [ ]:
# Addition
a=5;b=3
print("a+b =",a + b)
# Subtraction
print("a-b=", a - b)
# Multiplication
print("Multiplication:", a * b)
# Division
print("Division:", a / b)

a+b = 8
a-b= 2
Multiplication: 15
Division: 1.6666666666666667


### 3. Variables and Data Types
Introduction to different data types like integers, floats, strings and complex.

In [ ]:
# Integer
x=10
print("Data type of x is", type(x))
# Float
y = 3.14
print("Data type of y is", type(y))
# String
z = "Python"
print("Data type of z is", type(z))
# Complex
c=2+3j
print("Data type of c is", type(c))

Data type of x is <class 'int'>
Data type of y is <class 'float'>
Data type of z is <class 'str'>
Data type of c is <class 'complex'>


### 4. Lists
Creating and manipulating lists.

In [ ]:
# Creating a list
fruits = ["apple", "banana", "cherry"]
print("List:", fruits)
# Accessing elements
print("First fruit:", fruits[0])
# Adding an element
fruits.append("orange")
print("Updated list:", fruits)
# Removing an element
fruits.remove("banana")
print("List after removal:", fruits)
# Inserting an Element at a Specific Position in a List
fruits.insert(0,"banana")
print("New updated list:",fruits)

List: ['apple', 'banana', 'cherry']
First fruit: apple
Updated list: ['apple', 'banana', 'cherry', 'orange']
List after removal: ['apple', 'cherry', 'orange']
New updated list: ['banana', 'apple', 'cherry', 'orange']


### 5. Loops
Using for and while loops.

In [2]:
# For loop
for i in range(5):
  print("For loop iteration:", i)

For loop iteration: 0
For loop iteration: 1
For loop iteration: 2
For loop iteration: 3
For loop iteration: 4


In [3]:
# While loop
count = 0
while count <= 5:
  print("While loop iteration:", count)
  count += 1

While loop iteration: 0
While loop iteration: 1
While loop iteration: 2
While loop iteration: 3
While loop iteration: 4
While loop iteration: 5


### 6. Conditional Statements
Using if, elif and else statements.

In [ ]:
number = 0
if number > 0:
  print("Positive number")
elif number == 0:
  print("Zero")
else:
  print("Negative number")

Zero


### 7. Functions
Defining and calling functions.

In [ ]:
# Defining a function
def greet(name):
  return("Hello, "+name)
# Calling a function
print(greet("Alice"))
print(greet("Kalyani"))

Hello, Alice
Hello, Kalyani


## Basic Usage of Numpy

### Importing NumPy

In [7]:
import numpy as np

### 8. Creating Arrays using Numpy

In [8]:
# Creating a 1D array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


### 9. Creating special arrays using Numpy

In [9]:
# Creating an array of zeros
zeros = np.zeros((2, 3))
print("Array of Zeros:\n", zeros)
# Creating an array of ones
ones = np.ones((2, 3))
print("Array of Ones:\n", ones)
# Creating an array with a range of values
range_array = np.arange(10)
print("Range Array:", range_array)
# Creating an array with evenly spaced values
linspace_array = np.linspace(0, 1, 5)
print("Linspace Array:", linspace_array)

Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Array of Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Range Array: [0 1 2 3 4 5 6 7 8 9]
Linspace Array: [0.   0.25 0.5  0.75 1.  ]


### 10. Basic arithematic operations

In [10]:
# Element-wise addition
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Addition:", a + b)
# Element-wise subtraction
print("Subtraction:", a - b)
# Element-wise multiplication
print("Multiplication:", a * b)
# Element-wise division
print("Division:", a / b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


## APPLICATION PROBLEMS

####1. Problem Statement n a digital communication system, two discrete-time signals are received at a receiver. Each signal is represented as a sequence of amplitude values sampled at equal intervals. Given

• Signal 1 amplitudes: [2, 4, 6, 8]

• Signal 2 amplitudes: [1, 3, 5, 7]

### Task
• Import the NumPy library.

• Store both signals as NumPy arrays.

• Perform element-wise addition of the two signals.

• Display the resultant signal.

In [11]:
import numpy as np
signal1 = np.array([2, 4, 6, 8])
signal2 = np.array([1, 3, 5, 7])
resultant_signal = signal1 + signal2
print("Resultant Signal:", resultant_signal)

Resultant Signal: [ 3  7 11 15]


#### 2. An electronic temperature sensor outputs a voltage depending on the operating condition of a device. Voltage Classification

• Voltage < 2 V is Low Voltage

• Voltage between 2 V and 5 V is Safe Voltage

• Voltage > 5 V is High Voltage

• Given Sensor output voltage = 3.6 V

### Task
• Store the voltage value in a variable.

• Use conditional statements to classify the voltage level.

• Display the corresponding message.

In [12]:
voltage = 3.6
if voltage < 2:
  print("Low Voltage")
elif voltage <= 5:
  print("Safe Voltage")
else:
  print("High Voltage")

Safe Voltage


#### 3. An EC engineer is analyzing the frequency components present in a signal.Initially, only a few frequency components are detected.

Given

• Initial frequencies (in Hz): [100, 200, 300]

• A new frequency component 400 Hz is detected

• 200 Hz is identified as noise and must be removed.

• A missing low-frequency component 50 Hz must be added at the beginning.

### Task
• Create a list of initial frequencies.

• Add the new frequency at the end of the list.

• Remove the noise frequency.

• Insert the missing frequency at the first position.

• Display the final list of frequencies.

In [13]:
frequencies = [100, 200, 300]
print("Initial Frequencies:", frequencies)
frequencies.append(400)
print("After adding new frequency:", frequencies)
frequencies.remove(200)
print("After removing noise:", frequencies)
frequencies.insert(0, 50)
print("Final Frequency List:", frequencies)

Initial Frequencies: [100, 200, 300]
After adding new frequency: [100, 200, 300, 400]
After removing noise: [100, 300, 400]
Final Frequency List: [50, 100, 300, 400]


#### 4. In circuit analysis, electrical power consumed by a device is calculated using the formula P=V * I where
• V is voltage in volts

• I is current in amperes

Given

• Voltage = 12 V

• Current = 2 A

#### Task

• Define a function to calculate electrical power.

• Pass voltage and current as parameters.

• Return the calculated power.

• Display the power consumed.

In [14]:
def calculate_power(voltage, current):
  return voltage * current
power = calculate_power(12, 2)
print("Power consumed:", power, "Watts")

Power consumed: 24 Watts


#### 5. In digital image processing, an image is represented as a matrix where each element corresponds to a pixel intensity value.
Given

A grayscale image has the following pixel intensity values:

120 130 125

140 150 145

135 138 142

#### Task
• Import NumPy.

• Store the pixel values in a 2D NumPy array.

• Display the image matrix.

In [16]:
import numpy as np
image_matrix = np.array([[120, 130, 125],
                      [140, 150, 145],
                      [135, 138, 142]])
print("Image Matrix:")
print(image_matrix)

Image Matrix:
[[120 130 125]
 [140 150 145]
 [135 138 142]]
